name: Publish dev

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: ftp-action
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: public
